import { useState, useRef, useEffect } from "react";
import { useAppStore } from "@/store";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { ScrollArea } from "@/components/ui/scroll-area";
import { Send, Trash2, Bot, User, ChevronLeft, ChevronRight } from "lucide-react";
import { Badge } from "@/components/ui/badge";

export function ChatPanel() {
  const { messages, addMessage, clearChat, isGenerating, setIsGenerating, isConfigOpen, toggleConfig, isDebugOpen, toggleDebug } = useAppStore();
  const [input, setInput] = useState("");
  const scrollRef = useRef<HTMLDivElement>(null);

  useEffect(() => {
    if (scrollRef.current) {
      scrollRef.current.scrollTop = scrollRef.current.scrollHeight;
    }
  }, [messages]);

  const handleSend = () => {
    if (!input.trim() || isGenerating) return;
    
    // Add user message
    addMessage({
      role: "user",
      content: input
    });
    
    setInput("");
    setIsGenerating(true);
    
    // Simulate RAG response
    setTimeout(() => {
      addMessage({
        role: "assistant",
        content: "This is a simulated RAG response. In a real environment, this would be generated by OpenAI after retrieving relevant chunks from ChromaDB.",
        metadata: {
          chunksRetrieved: 3,
          tokens: 150,
          webResearchUsed: false
        }
      });
      setIsGenerating(false);
    }, 1500);
  };

  const handleKeyDown = (e: React.KeyboardEvent) => {
    if (e.key === "Enter" && !e.shiftKey) {
      e.preventDefault();
      handleSend();
    }
  };

  return (
    <div className="flex flex-col h-full bg-card relative">
      <div className="h-14 flex items-center justify-between px-4 border-b bg-background/50 shrink-0">
        <div className="flex items-center">
          {!isConfigOpen && (
            <Button variant="ghost" size="icon" onClick={toggleConfig} title="Open Configuration Panel" className="h-8 w-8 shrink-0 -ml-2">
              <ChevronRight className="w-5 h-5 text-muted-foreground" />
            </Button>
          )}
        </div>
        <div className="flex items-center gap-2">
          <Button variant="ghost" size="sm" onClick={clearChat} title="Clear Chat" className="inline-flex items-center justify-center gap-2 whitespace-nowrap font-medium transition-colors focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-ring disabled:pointer-events-none disabled:opacity-50 [&_svg]:pointer-events-none [&_svg]:size-4 [&_svg]:shrink-0 hover-elevate active-elevate-2 border border-transparent min-h-8 rounded-md px-3 text-xs h-8 hover:text-foreground text-[#ffffff] bg-[#0048ade6]">
            Clear
          </Button>
          {!isDebugOpen && (
            <Button variant="ghost" size="icon" onClick={toggleDebug} title="Open Debug Panel" className="h-8 w-8 shrink-0 -mr-2">
              <ChevronLeft className="w-5 h-5 text-muted-foreground" />
            </Button>
          )}
        </div>
      </div>
      <ScrollArea className="flex-1 p-4" ref={scrollRef}>
        <div className="space-y-6 max-w-3xl mx-auto pb-4">
          {messages.map((msg) => (
            <div 
              key={msg.id} 
              className={`flex gap-4 ${msg.role === "user" ? "flex-row-reverse" : "flex-row"}`}
            >
              <div className={`w-8 h-8 rounded-full flex items-center justify-center shrink-0 ${
                msg.role === "user" ? "bg-primary text-primary-foreground" : "bg-secondary text-secondary-foreground"
              }`}>
                {msg.role === "user" ? <User size={16} /> : <Bot size={16} />}
              </div>
              
              <div className={`flex flex-col gap-1 max-w-[80%] ${msg.role === "user" ? "items-end" : "items-start"}`}>
                <div className={`px-4 py-3 rounded-2xl ${
                  msg.role === "user" 
                    ? "bg-primary text-primary-foreground rounded-tr-sm" 
                    : "bg-secondary text-secondary-foreground rounded-tl-sm"
                }`}>
                  <div className="prose prose-sm dark:prose-invert max-w-none break-words whitespace-pre-wrap leading-relaxed font-sans">
                    {msg.content}
                  </div>
                </div>
                
                {msg.metadata && msg.role === "assistant" && (
                  <div className="flex items-center gap-2 mt-1">
                    <span className="text-[10px] text-muted-foreground flex items-center gap-1">
                      {msg.metadata.chunksRetrieved} chunks
                    </span>
                    {msg.metadata.webResearchUsed && (
                      <Badge variant="outline" className="text-[9px] px-1 py-0 h-4 bg-accent text-accent-foreground border-accent-border">
                        Web Research
                      </Badge>
                    )}
                  </div>
                )}
              </div>
            </div>
          ))}
          {isGenerating && (
            <div className="flex gap-4">
              <div className="w-8 h-8 rounded-full bg-secondary text-secondary-foreground flex items-center justify-center shrink-0">
                <Bot size={16} />
              </div>
              <div className="px-4 py-3 rounded-2xl bg-secondary text-secondary-foreground rounded-tl-sm flex items-center gap-2">
                <div className="w-2 h-2 rounded-full bg-muted-foreground/40 animate-pulse"></div>
                <div className="w-2 h-2 rounded-full bg-muted-foreground/40 animate-pulse delay-150"></div>
                <div className="w-2 h-2 rounded-full bg-muted-foreground/40 animate-pulse delay-300"></div>
              </div>
            </div>
          )}
        </div>
      </ScrollArea>
      <div className="p-4 bg-background border-t">
        <div className="max-w-3xl mx-auto relative flex items-center">
          <Input 
            value={input}
            onChange={(e) => setInput(e.target.value)}
            onKeyDown={handleKeyDown}
            placeholder="Ask about the source material..."
            className="pr-12 py-6 rounded-xl border-muted bg-card shadow-sm focus-visible:ring-1 focus-visible:ring-primary/30"
          />
          <Button 
            size="icon" 
            className="absolute right-2 h-8 w-8 rounded-lg" 
            onClick={handleSend}
            disabled={!input.trim() || isGenerating}
          >
            <Send className="w-4 h-4" />
          </Button>
        </div>
        <div className="text-center mt-2">
          <p className="text-[10px] text-muted-foreground font-mono">True North Applied Technologies</p>
        </div>
      </div>
    </div>
  );
}
